import { ref } from 'vue'

export type UiLanguage = 'en' | 'zh-CN'

const UI_LANGUAGE_STORAGE_KEY = 'codex-web-local.ui-language.v1'

const zhCN: Record<string, string> = {
  'English': '英语',
  'Simplified Chinese': '简体中文',
  'Search threads': '搜索线程',
  'Filter threads...': '筛选线程...',
  'Clear search': '清除搜索',
  'Chats': '聊天',
  'Projects': '项目',
  'Pinned': '已固定',
  'Chats first': '聊天优先',
  'Sort by': '排序',
  'Created': '创建时间',
  'Updated': '更新时间',
  'New chat': '新聊天',
  'New conversation': '新对话',
  'No chats': '没有聊天',
  'Skills Hub': '技能中心',
  'Expand accounts': '展开账户',
  'Collapse accounts': '折叠账户',
  'Accounts': '账户',
  'Reloading…': '重新加载中…',
  'Reload': '重新加载',
  'Loading…': '加载中…',
  'Run `codex login`, then click reload.': '先运行 `codex login`，然后点击重新加载。',
  'Account': '账户',
  'Workspace': '工作区',
  'Require ⌘ + enter to send': '需要 ⌘ + Enter 才发送',
  'When busy, send as': '忙碌时发送方式',
  'Steer': '引导',
  'Queue': '排队',
  'Appearance': '外观',
  'System': '跟随系统',
  'Dark': '深色',
  'Light': '浅色',
  'Chat width': '聊天宽度',
  'Click to toggle dictation': '点击切换语音输入',
  'Auto send dictation': '语音输入后自动发送',
  'Provider': '提供方',
  'Choose the API provider for the Codex backend': '选择 Codex 后端使用的 API 提供方',
  'OpenRouter API key': 'OpenRouter API Key',
  'Get API key': '获取 API Key',
  'Remove OpenRouter key': '移除 OpenRouter key',
  'Set': '设置',
  'Save': '保存',
  'API format': 'API 格式',
  'OpenRouter API format': 'OpenRouter API 格式',
  'Responses': 'Responses',
  'Completions': 'Completions',
  'OpenCode Zen API key': 'OpenCode Zen API Key',
  'Custom endpoint URL': '自定义端点 URL',
  'API key': 'API Key',
  'Custom endpoint API format': '自定义端点 API 格式',
  'UI language': '界面语言',
  'Choose the interface language for the app.': '选择应用界面语言。',
  'Dictation language': '听写语言',
  'Auto-detect': '自动检测',
  'Search language...': '搜索语言...',
  'Telegram': 'Telegram',
  'Bot token': 'Bot Token',
  'Allowed Telegram user IDs': '允许的 Telegram 用户 ID',
  'Put one Telegram user ID per line or separate them with commas. Use `*` to allow all Telegram users. Unauthorized users will see their own ID in the rejection message so they can copy it here.': '每行填写一个 Telegram 用户 ID，或用逗号分隔。使用 `*` 可允许所有 Telegram 用户。未授权用户会在拒绝消息中看到自己的 ID，方便复制到这里。',
  'Saving…': '保存中…',
  'Save Telegram config': '保存 Telegram 配置',
  'Context': '上下文',
  'Worktree name and version': '工作树名称和版本',
  'Context window:': '背景信息窗口:',
  '{used}% used ({remaining}% remaining)': '{used}% 已用（剩余 {remaining}%）',
  'Used {used} tokens of {total}': '已用 {used} 标记，共 {total}',
  'Context window: {percent}. {tokens}': '背景信息窗口：{percent}。{tokens}',
  'Settings': '设置',
  'Connect mobile device': '连接手机',
  'Toggle terminal': '切换终端',
  'Open terminal': '打开终端',
  'Terminal command': '终端命令',
  'No commands': '没有命令',
  'Search branches...': '搜索分支...',
  "Let's build": '开始构建',
  'Choose folder': '选择文件夹',
  'Quick search project': '快速搜索项目',
  'Selected folder': '已选文件夹',
  'Select folder': '选择文件夹',
  'Create Project': '创建项目',
  'Create or clone': '创建或克隆',
  'Create or clone project': '创建或克隆项目',
  'Project source': '项目来源',
  'New project': '新项目',
  'Destination folder': '目标文件夹',
  'New project name': '新项目名称',
  'GitHub repository URL': 'GitHub 仓库 URL',
  'Create project': '创建项目',
  'Creating…': '创建中…',
  'Clone repository': '克隆仓库',
  'Clone from GitHub': '从 GitHub 克隆',
  'Cloning…': '克隆中…',
  'Current folder': '当前文件夹',
  'Unavailable': '不可用',
  'Opening…': '打开中…',
  'Open': '打开',
  'Show hidden folders': '显示隐藏文件夹',
  'New folder': '新建文件夹',
  'Folder name': '文件夹名称',
  'Filter folders...': '筛选文件夹...',
  'Retry': '重试',
  'Loading folders…': '加载文件夹中…',
  'No folders match this filter.': '没有匹配此筛选条件的文件夹。',
  'No subfolders found here.': '这里没有子文件夹。',
  'Base branch': '基础分支',
  'Select branch': '选择分支',
  'Loading branches…': '加载分支中…',
  'No Git branches found for this folder.': '此文件夹未找到 Git 分支。',
  'Local project': '本地项目',
  'New worktree': '新工作树',
  'Service worker registration failed.': 'Service Worker 注册失败。',
  'No matching files': '没有匹配的文件',
  'Add photos & files': '添加图片和文件',
  'Request approval': '请求批准',
  'Always ask before editing external files or using the internet': '编辑外部文件和使用互联网时始终询问',
  'Approve for me': '替我审批',
  'Only ask for detected risky operations': '仅对检测到的风险操作请求批准',
  'Full access': '完全访问',
  'Access the internet and any file on this computer without restriction': '可不受限制地访问互联网和您电脑上的任何文件',
  'Add folder': '添加文件夹',
  'Take photo': '拍照',
  'In-progress send': '执行中发送',
  'Fast mode': '快速模式',
  'Plan mode': '规划模式',
  'Agent proposes a plan before acting': '代理在执行前先提出计划',
  'Model': '模型',
  'Low': '低',
  'Medium': '中',
  'High': '高',
  'Extra high': '超高',
  'Search models...': '搜索模型...',
  'No matching models': '没有匹配的模型',
  'Skills': '技能',
  'Search skills...': '搜索技能...',
  'Search skills': '搜索技能',
  'Search skills and prompts...': '搜索技能和提示词...',
  'Thinking': '思考强度',
  'Reasoning': '推理',
  'Saving thread before stop is available': '线程保存后才能停止',
  'Stop': '停止',
  'Queue message': '加入队列',
  'Send message': '发送消息',
  'Send': '发送',
  'Drop images or files': '拖放图片或文件',
  'Selected image': '已选图片',
  'Loading messages...': '加载消息中...',
  'No messages in this thread yet.': '这个线程里还没有消息。',
  'Load earlier messages': '加载更早的消息',
  'Plan': '计划',
  'Updating': '更新中',
  'Edit this message': '编辑此消息',
  'Edit message': '编辑消息',
  'Fork thread from this response': '从此回复分叉线程',
  'Fork': '分叉',
  'Response copied': '回复已复制',
  'Copy response': '复制回复',
  'Jump to latest': '跳转到最新',
  'Jump to latest output': '跳转到最新输出',
  'Close image preview': '关闭图片预览',
  'Expanded message image': '放大消息图片',
  'Changed files': '已更改文件',
  'Close diff viewer': '关闭 diff 查看器',
  'No diff available': '没有可用 diff',
  'This summary was restored from the final answer text, but the thread history does not include patch diff content for this file.': '此摘要是从最终回答文本恢复的，但线程历史中不包含该文件的补丁 diff 内容。',
  'Review': '审查',
  'Commit': '提交',
  'Close review pane': '关闭审查面板',
  'Compare': '比较',
  'Branch': '分支',
  'Changes': '更改',
  'Loading review state': '加载审查状态中',
  'This folder is not a Git repository': '此文件夹不是 Git 仓库',
  'Initialize Git to review local changes and run Codex review.': '初始化 Git 后即可审查本地更改并运行 Codex review。',
  'Initializing…': '初始化中…',
  'Initialize Git': '初始化 Git',
  'Base branch unavailable': '基础分支不可用',
  'Could not resolve `origin/HEAD`, `main`, or `master` for this repository.': '无法为此仓库解析 `origin/HEAD`、`main` 或 `master`。',
  'No changes in this scope': '此范围内没有更改',
  'No file changes in this commit.': '此提交中没有文件更改。',
  'Your current workspace is clean.': '当前工作区很干净。',
  'No merge diff found against the base branch.': '未找到相对基础分支的合并 diff。',
  'No unified diff available.': '没有可用的统一 diff。',
  'Summary': '摘要',
  'Added': '新增',
  'Deleted': '删除',
  'Renamed': '重命名',
  'Modified': '修改',
  'Repository review': '仓库审查',
  'Staged changes': '已暂存更改',
  'Workspace changes': '工作区更改',
  'Unstage all': '全部取消暂存',
  'Stage all': '全部暂存',
  'Revert all': '全部还原',
  'Unstage file': '取消暂存文件',
  'Stage file': '暂存文件',
  'Revert file': '还原文件',
  'Unstage hunk': '取消暂存代码块',
  'Stage hunk': '暂存代码块',
  'Revert hunk': '还原代码块',
  'Failed to load review snapshot': '加载审查快照失败',
  'Failed to apply review action': '应用审查操作失败',
  'Failed to initialize Git': '初始化 Git 失败',
  'Reviewing current changes': '正在审查当前更改',
  'Failed to start review': '启动审查失败',
  'Review in progress': '审查进行中',
  'Failed to load review result': '加载审查结果失败',
  'pin': '固定',
  'Worktree thread': '工作树线程',
  'Threads': '线程',
  'Organize threads': '整理线程',
  'Organize': '整理',
  'By project': '按项目',
  'Chronological list': '按时间顺序',
  'No matching threads': '没有匹配的线程',
  'Loading threads...': '加载线程中...',
  'Edit name': '编辑名称',
  'Remove': '移除',
  'Project name': '项目名称',
  'No threads': '没有线程',
  'Thread title': '线程标题',
  'Rename thread': '重命名线程',
  'Make it short and recognizable.': '尽量简短且易识别。',
  'Add title...': '输入标题...',
  'Cancel': '取消',
  'Delete thread': '删除线程',
  'Thread automation': '线程自动化',
  'This creates a heartbeat automation attached to the selected thread.': '这会创建一个附加到所选线程的心跳自动化。',
  'Name': '名称',
  'Automation name': '自动化名称',
  'Prompt': '提示词',
  'Search prompt...': '搜索提示词...',
  'Describe what the automation should do': '描述自动化需要执行的内容',
  'Schedule (RRULE)': '计划（RRULE）',
  'Status': '状态',
  'Active': '启用',
  'Paused': '暂停',
  'Expand sidebar': '展开侧边栏',
  'Collapse sidebar': '折叠侧边栏',
  'Start new thread': '新建线程',
  'Primary navigation': '主导航',
  'No skills found': '未找到技能',
  'No results': '没有结果',
  'Approval choices': '审批选项',
  'No, and tell Codex what to do differently': '不允许，并告诉 Codex 应如何调整',
  'Skip': '跳过',
  'Server': '服务器',
  'Open authorization link': '打开授权链接',
  'Value': '值',
  'Choice': '选项',
  'Select true or false': '选择 true 或 false',
  'True': '真',
  'False': '假',
  'Select an option': '选择一个选项',
  'Decline': '拒绝',
  'Continue': '继续',
  'Other answer': '其他答案',
  'Fail Tool Call': '使工具调用失败',
  'Success (Empty)': '成功（空结果）',
  'Return Empty Result': '返回空结果',
  'New terminal': '新终端',
  'New': '新建',
  'Hide terminal': '隐藏终端',
  'Thread display settings': '线程显示设置',
  'Close': '关闭',
  'Edit queued message': '编辑排队消息',
  'Send now without interrupting work': '立即发送且不中断当前工作',
  'Delete queued message': '删除排队消息',
  'AppServer API': 'AppServer API',
  'Loading method catalog...': '加载方法目录中...',
  'Disabled': '已禁用',
  'Installed': '已安装',
  'Browse files': '浏览文件',
  'Thread menu': '线程菜单',
  'Project menu': '项目菜单',
  'Show less': '显示更少',
  'Show more': '显示更多',
  'Manage automations…': '管理自动化…',
  'Add automation…': '添加自动化…',
  'Add automation': '添加自动化',
  'Edit automation': '编辑自动化',
  'Add another automation': '再添加一个自动化',
  'Automation target type': '自动化目标类型',
  'Automation schedule type': '自动化计划类型',
  'Project automation': '项目自动化',
  'Project automations': '项目自动化',
  'Thread automations': '线程自动化',
  'Existing chat': '现有聊天',
  'Select project': '选择项目',
  'Select chat': '选择聊天',
  'Search projects': '搜索项目',
  'Search chats': '搜索聊天',
  'Interval': '间隔',
  'Run every day at': '每天运行时间',
  'Run every': '每隔',
  'Unit': '单位',
  'Run now': '立即运行',
  'Running…': '运行中…',
  'Automation saved.': '自动化已保存。',
  'Automation run queued.': '自动化运行已加入队列。',
  'Failed to save automation': '保存自动化失败',
  'Failed to remove automation': '移除自动化失败',
  'Failed to run automation': '运行自动化失败',
  'Failed to delete project automation': '删除项目自动化失败',
  'Project automation requires a resolved absolute project path.': '项目自动化需要解析后的绝对项目路径。',
  'This creates a heartbeat automation attached to the selected chat.': '这会创建一个附加到所选聊天的心跳自动化。',
  'This creates a project automation attached to the selected project folder.': '这会创建一个附加到所选项目文件夹的项目自动化。',
  'This creates project automations attached to the selected project folder.': '这会创建附加到所选项目文件夹的项目自动化。',
  'This creates heartbeat automations attached to the selected thread.': '这会创建附加到所选线程的心跳自动化。',
  'Confirm': '确认',
  'Confirm delete': '确认删除',
  'Archive and remove': '归档并移除',
  'Archive chat and remove automations?': '归档聊天并移除自动化？',
  'Delete': '删除',
  'Delete thread?': '删除线程？',
  'This will archive the thread "{title}" and remove the attached heartbeat automations.': '这会归档线程“{title}”，并移除附加的心跳自动化。',
  'This will archive the thread "{title}". You can find it later in archived threads.': '这会归档线程“{title}”。之后你可以在已归档线程中找到它。',
  'Copy path': '复制路径',
  'Copy chat': '复制聊天',
  'Open this chat before copying': '复制前请先打开此聊天',
  'Create chat fork': '创建聊天分叉',
  'Pin thread': '固定线程',
  'Unpin thread': '取消固定线程',
  'Rename project': '重命名项目',
  'New thread': '新线程',
  'Start new thread {project}': '在 {project} 中新建线程',
  'Resize sidebar': '调整侧边栏宽度',
  'Not scheduled': '未计划',
  '{count} automations • {activeCount} active': '{count} 个自动化 • {activeCount} 个启用',
  '{name} • Next run: {nextRun}': '{name} • 下次运行：{nextRun}',
  'RRULE: {rrule} · runs daily at {time}': 'RRULE: {rrule} · 每天 {time} 运行',
  'RRULE: {rrule} · runs every {interval} minutes': 'RRULE: {rrule} · 每 {interval} 分钟运行',
  'RRULE: {rrule} · runs every {interval} hours': 'RRULE: {rrule} · 每 {interval} 小时运行',
  'RRULE: {rrule} · runs every {interval} days': 'RRULE: {rrule} · 每 {interval} 天运行',
  'RRULE: {rrule}': 'RRULE: {rrule}',
  'RRULE is required.': '必须填写 RRULE。',
  'minutes': '分钟',
  'hours': '小时',
  'days': '天',
  'Loading skill contents...': '加载技能内容中...',
  'Show all': '显示全部',
  'Hide all': '隐藏全部',
  'No types yet': '还没有类型',
  'Manage installed skills on this machine': '管理此机器上已安装的技能',
  'Skills Sync (GitHub)': '技能同步（GitHub）',
  'Connected': '已连接',
  'Logged in as': '已登录为',
  'Not connected': '未连接',
  'Startup': '启动',
  'Action': '动作',
  'Manual sync': '手动同步',
  'GitHub device login': 'GitHub 设备登录',
  'and enter code:': '并输入代码：',
  'Login with GitHub': '使用 GitHub 登录',
  'Device Login': '设备登录',
  'Logout GitHub': '退出 GitHub',
  'Syncing...': '同步中...',
  'Startup Sync': '启动同步',
  'Pulling...': '拉取中...',
  'Pull': '拉取',
  'Pushing...': '推送中...',
  'Push': '推送',
  'Installed ({count})': '已安装（{count}）',
  'Find skills': '查找技能',
  'Search the Skills registry with npx skills find.': '使用 npx skills find 搜索 Skills 注册表。',
  'Searching...': '搜索中...',
  'Search results ({count})': '搜索结果（{count}）',
  'No matching skills found.': '未找到匹配的技能。',
  'No installed skills found.': '未找到已安装的技能。',
  'Continue in': '运行方式',
  'Search daily': '搜索（日）',
  'Search weekly': '搜索（周）',
  'Search monthly': '搜索（月）',
  'Trending daily': '热门（日）',
  'Trending weekly': '热门（周）',
  'Trending monthly': '热门（月）',
  'Newest': '最新',
  'A-Z': 'A-Z',
  'Loading skills...': '加载技能中...',
  'Choose a thread': '选择一个线程',
  'New worktree branch will start from {branch}.': '新工作树分支将从 {branch} 开始。',
  'Local project uses the selected folder directly. New worktree creates an isolated Git worktree before the first prompt.': '本地项目会直接使用所选文件夹。新工作树会在第一次提问前创建一个隔离的 Git worktree。',
  'Not configured': '未配置',
  'Online': '在线',
  'Configured (offline)': '已配置（离线）',
  'allow all users': '允许所有用户',
  'allowed user(s)': '个允许用户',
  'chat(s)': '个聊天',
  'thread(s)': '个线程',
  'error': '错误',
  'unknown': '未知',
  'Switching…': '切换中…',
  'Switch': '切换',
  'Removing…': '移除中…',
  'Click again to remove': '再次点击以移除',
  '402 Payment Required': '402 需要付费',
  'weekly remaining': '周剩余额度',
  'Unlimited credits': '无限额度',
  'credits': '额度',
  'Loading quota…': '加载额度中…',
  'Quota unavailable': '额度不可用',
  'Fetching account details…': '获取账户详情中…',
  'Unavailable account': '不可用账户',
  'Waiting for Codex thread/tokenUsage/updated events for this thread.': '等待此线程的 Codex tokenUsage 更新事件。',
  'Current context usage': '当前上下文使用量',
  'Cumulative thread usage': '累计线程使用量',
  'Model context window': '模型上下文窗口',
  'Remaining context': '剩余上下文',
  'tokens': 'tokens',
  'Model context window is unavailable in the latest usage event.': '最新使用事件中未提供模型上下文窗口。',
  'Awaiting data': '等待数据中',
  'left': '剩余',
  'used': '已用',
  'Updates after the next token usage event': '下次 token 使用事件后更新',
  'Window size unavailable': '窗口大小不可用',
  'Telegram bot token is required.': '需要填写 Telegram Bot Token。',
  'At least one allowed Telegram user ID or * is required.': '至少需要一个允许的 Telegram 用户 ID 或 `*`。',
  'Telegram bot configured. Only allowlisted Telegram users can use the bridge.': 'Telegram 机器人已配置。只有白名单中的 Telegram 用户可以使用桥接。',
  'Failed to connect Telegram bot': '连接 Telegram 机器人失败',
  'Failed to load accounts': '加载账户失败',
  'Failed to refresh accounts': '刷新账户失败',
  'Login': '登录',
  'Starting login…': '正在启动登录…',
  'Open login URL': '打开登录链接',
  'Paste localhost callback URL': '粘贴 localhost 回调 URL',
  'Complete Codex login': '完成 Codex 登录',
  'Finish login in the browser, then paste the localhost callback URL here.': '在浏览器中完成登录，然后在这里粘贴 localhost 回调 URL。',
  'Complete': '完成',
  'Completing…': '正在完成…',
  'Failed to start Codex login': '启动 Codex 登录失败',
  'Failed to complete Codex login': '完成 Codex 登录失败',
  'Click Login, or run `codex login`, then click reload.': '点击登录，或运行 `codex login`，然后点击重新加载。',
  'Finish the current turn and pending requests before switching accounts.': '请先完成当前轮次并处理待处理请求后再切换账户。',
  'Failed to switch account': '切换账户失败',
  'Finish the current turn and pending requests before removing the active account.': '请先完成当前轮次并处理待处理请求后再移除当前活动账户。',
  'Failed to remove account': '移除账户失败',
  'enabled': '已启用',
  'disabled': '已禁用',
  'Saving speed setting...': '保存速度设置中...',
  'Fast': '快速',
  'About 1.5x faster, with credits used at 2x': '速度约提升 1.5 倍，额度消耗为 2 倍',
  'Default speed with normal credit usage': '默认速度，按正常额度消耗',
  'Stop dictation': '停止听写',
  'Click to dictate': '点击开始听写',
  'Hold to dictate': '按住听写',
  'failed': '失败',
  'attaching': '正在附加',
  'Attaching': '正在附加',
  'Attaching file...': '正在附加文件...',
  'files...': '个文件...',
  'attached': '已附加',
  'Could not attach file.': '无法附加文件。',
  'Could not attach': '无法附加',
  'files.': '个文件。',
  'Select a thread to send a message': '选择一个线程后才能发送消息',
  'Loading models for plan mode...': '正在为规划模式加载模型...',
  'Type a message... (@ for files)': '输入消息...（@ 选择文件）',
  'Freeform input': '随心输入',
  'Request follow-up changes': '要求后续变更',
  'Hide': '隐藏',
  'Terminal': '终端',
  'Terminal input failed': '终端输入失败',
  'Terminal attach failed': '终端附加失败',
  'Creating worktree': '创建工作树',
  'Creating a worktree and running setup.': '正在创建工作树并执行初始化。',
  'Worktree setup failed': '工作树初始化失败',
  'Unable to create worktree. Try again or switch to Local project.': '无法创建工作树。请重试，或切换到本地项目。',
  'Edit': '编辑',
  'image': '图片',
  'images': '图片',
  'file': '文件',
  'files': '文件',
  'skill': '技能',
  'skills': '技能',
  '(empty queued message)': '（空的排队消息）',
  'Files': '文件',
  'Unstaged': '未暂存',
  'Staged': '已暂存',
  'Refresh': '刷新',
  'Against': '对比',
  'selected': '已选',
  'Reject Request': '拒绝请求',
  'Uninstalling...': '卸载中...',
  'Uninstall': '卸载',
  'Installing...': '安装中...',
  'Install': '安装',
  'Disable': '禁用',
  'Enable': '启用',
  'When enabled, press Enter to send. When disabled, use Command+Enter to send.': '启用时按 Enter 发送；禁用时使用 Command+Enter 发送。',
  'If a turn is still running, choose whether a new prompt should steer the current turn or be queued.': '如果当前轮次仍在运行，选择新提示是引导当前轮次还是加入队列。',
  'Switch between system theme, light mode, and dark mode.': '在跟随系统、浅色和深色主题之间切换。',
  'Choose how wide the conversation column and composer can grow on desktop screens.': '选择桌面端会话列和输入框的最大宽度。',
  'Use click-to-start and click-to-stop dictation instead of hold-to-talk.': '使用点击开始/停止听写，而不是按住说话。',
  'Automatically send transcribed dictation when recording stops.': '录音停止后自动发送转写结果。',
  'Choose transcription language or keep auto-detect.': '选择转写语言，或保持自动检测。',
  'Standard': '标准',
  'Speed': '速度',
  'Wide': '宽',
  'Extra wide': '超宽',
  ' If there are multiple accounts, prefer `{wordId}`.': ' 如果有多个账户，优先使用 `{wordId}`。',
  'Add new prompt': '添加新提示词',
  'App': '应用',
  'Apps': '应用',
  'Apps APIs unavailable in this Codex CLI. Update Codex CLI to manage apps.': '当前 Codex CLI 不支持应用 API。请更新 Codex CLI 以管理应用。',
  'Apps needing auth': '需要授权的应用',
  'Auth': '授权',
  'Auth unsupported': '不支持授权',
  'Authenticate': '授权',
  'Authenticated': '已认证',
  'Automation details': '自动化详情',
  'Automations': '自动化',
  'Availability': '空闲时间',
  'Bearer token (optional)': 'Bearer 令牌（可选）',
  'Bearer token': 'Bearer 令牌',
  'Branch commits': '分支提交',
  'Branches': '分支',
  'Capabilities': '功能',
  'ChatGPT Plus': 'ChatGPT Plus',
  'Check what is next, find open time, and turn follow-ups into calendar blocks.': '查看接下来的安排、寻找空闲时间，并把后续事项转成日历时间块。',
  'Checkout': '检出',
  'Close Composio detail': '关闭 Composio 详情',
  'Close plugin detail': '关闭插件详情',
  'Codex': 'Codex',
  'Comments': '评论',
  'Commit files': '提交文件',
  'Composio CLI installed': 'Composio CLI 已安装',
  'Composio CLI is not installed in this environment.': '此环境中未安装 Composio CLI。',
  'Composio CLI login started': 'Composio CLI 登录已开始',
  'Composio CLI shares the login and connections from this machine.': 'Composio CLI 使用这台机器上的登录状态和连接。',
  'Composio is installed locally. Login to browse the live catalog, connect your accounts, and try simple actions from this machine.': 'Composio 已在本机安装。登录后即可浏览实时目录、连接账户，并从这台机器尝试简单操作。',
  'Composio workspace': 'Composio 工作区',
  'Connect': '连接',
  'Connect everyday apps like Gmail, Calendar, Reddit, YouTube, and Drive.': '连接 Gmail、日历、Reddit、YouTube、Drive 等常用应用。',
  'Connection required': '需要连接',
  'Connections': '连接',
  'Connector': '连接器',
  'Connector catalog preview': '连接器目录预览',
  'Copied': '已复制',
  'Copied commit ref': '已复制提交引用',
  'Copy': '复制',
  'Create a new automation': '创建新的自动化',
  'Current branch': '当前分支',
  'Custom endpoint': '自定义端点',
  'Custom schedule': '自定义计划',
  'Daily': '每天',
  'Date': '日期',
  'No branch': '无分支',
  'Details': '详情',
  'Disable plan mode': '关闭规划模式',
  'Dismiss': '关闭',
  'Directory sections': '目录分区',
  'Download': '下载',
  'Drag to reorder queued message': '拖动以重排排队消息',
  'Drafts': '草稿',
  'Docs': '文档',
  'Ecosystem directory': '生态目录',
  'Email': '邮件',
  'Enable plan mode': '启用规划模式',
  'Events': '事件',
  'Events and availability': '事件和空闲时间',
  'Every minute': '每分钟',
  'Every {count} minutes': '每 {count} 分钟',
  'Every {count} hours': '每 {count} 小时',
  'Expired': '已过期',
  'Exit full screen composer': '退出全屏输入框',
  'Expand composer': '展开输入框',
  'Explore Plugins & Apps': '浏览插件和应用',
  'Export Project': '导出项目',
  'Exporting': '正在导出',
  'Failed': '失败',
  'Failed to connect {name}': '连接 {name} 失败',
  'Failed to install Composio CLI': '安装 Composio CLI 失败',
  'Failed to install plugin': '安装插件失败',
  'Failed to load Composio connector': '加载 Composio 连接器失败',
  'Failed to load Composio connectors': '加载 Composio 连接器失败',
  'Failed to load MCP servers': '加载 MCP 服务器失败',
  'Failed to load apps': '加载应用失败',
  'Failed to load automations': '加载自动化失败',
  'Failed to load plugin': '加载插件失败',
  'Failed to load plugins': '加载插件失败',
  'Failed to reload MCP servers': '重新加载 MCP 服务器失败',
  'Failed to start Composio login': '启动 Composio 登录失败',
  'Failed to start login for {name}': '启动 {name} 登录失败',
  'Failed to uninstall plugin': '卸载插件失败',
  'Failed to update app': '更新应用失败',
  'Failed to update plugin': '更新插件失败',
  'Failed to share project. Use Download instead.': '分享项目失败。请改用下载。',
  'Files, docs, folders': '文件、文档、文件夹',
  'Find emails, summarize threads, draft replies, and pull attachment context into a chat.': '查找邮件、总结会话、起草回复，并把附件上下文带入聊天。',
  'Find files, read shared docs, and bring Drive context into a Codex thread.': '查找文件、读取共享文档，并把 Drive 上下文带入 Codex 线程。',
  'GPT Plus account required': '需要 GPT Plus 账户',
  'Git branch': 'Git 分支',
  'Heartbeat': '心跳',
  'Hook Codex up to Gmail, Calendar, GitHub, Slack, Browser Use, and more so it can actually help with real work right away.': '将 Codex 连接到 Gmail、日历、GitHub、Slack、Browser Use 等服务，让它能立即协助真实工作。',
  'Hourly': '每小时',
  'Inbox, drafts, attachments': '收件箱、草稿、附件',
  'Import Project': '导入项目',
  'Importing…': '正在导入…',
  'Install Composio': '安装 Composio',
  'Installed skills ({count})': '已安装技能（{count}）',
  'Issue detected': '检测到问题',
  'Load more': '加载更多',
  'Loading Composio connectors...': '正在加载 Composio 连接器...',
  'Loading MCP servers...': '正在加载 MCP 服务器...',
  'Loading apps...': '正在加载应用...',
  'Loading automations...': '正在加载自动化...',
  'Loading branch...': '正在加载分支...',
  'Loading connector...': '正在加载连接器...',
  'Loading commits...': '正在加载提交...',
  'Loading files...': '正在加载文件...',
  'Loading plugin...': '正在加载插件...',
  'Loading plugins...': '正在加载插件...',
  'Loading...': '正在加载...',
  'Logged in': '已登录',
  'Login required': '需要登录',
  'Login to Composio': '登录 Composio',
  'Look up channel details, inspect video metadata, and help manage comment workflows.': '查询频道详情、检查视频元数据，并帮助管理评论流程。',
  'MCP servers': 'MCP 服务器',
  'MCP servers reloaded': 'MCP 服务器已重新加载',
  'MCP status APIs unavailable in this Codex CLI. Update Codex CLI to inspect MCP servers.': '当前 Codex CLI 不支持 MCP 状态 API。请更新 Codex CLI 以检查 MCP 服务器。',
  'MCPs': 'MCP',
  'Manage': '管理',
  'methods': '个方法',
  'New automation': '新建自动化',
  'New in Codex': 'Codex 新功能',
  'Next': '下次',
  'No automations yet': '还没有自动化',
  'No Composio connectors found.': '未找到 Composio 连接器。',
  'No MCP servers configured.': '未配置 MCP 服务器。',
  'No apps found.': '未找到应用。',
  'No auth': '无需授权',
  'No auth required': '无需授权',
  'No branches found.': '未找到分支。',
  'No commits found.': '未找到提交。',
  'No file changes.': '没有文件变更。',
  'No linked accounts yet.': '还没有关联账户。',
  'No login URL returned for {name}': '{name} 未返回登录链接',
  'No plugins found.': '未找到插件。',
  'No saved accounts yet. Run `codex login`, then click reload.': '还没有保存的账户。运行 `codex login`，然后点击重新加载。',
  'OpenCode Zen': 'OpenCode Zen',
  'Open dashboard': '打开控制台',
  'OpenAI catalog': 'OpenAI 目录',
  'OpenRouter': 'OpenRouter',
  'Opened {name} authorization': '已打开 {name} 授权',
  'Opening...': '正在打开...',
  'Overview': '概览',
  'Pending': '待处理',
  'Plugin': '插件',
  'Plugins': '插件',
  'Plugin APIs unavailable in this Codex CLI. Update Codex CLI to use plugin catalog features.': '当前 Codex CLI 不支持插件 API。请更新 Codex CLI 以使用插件目录功能。',
  'Plugins are here': '插件已上线',
  'Plugins, apps, MCPs': '插件、应用、MCP',
  'Popular': '热门',
  'Posts': '帖子',
  'Posts, comments, communities': '帖子、评论、社区',
  'Posts, replies, profiles': '帖子、回复、资料',
  'Preparing project ZIP...': '正在准备项目 ZIP...',
  'Preparing...': '正在准备...',
  'Preview': '预览',
  'Profiles': '资料',
  'Project': '项目',
  'Prompt content': '提示词内容',
  'Prompt name': '提示词名称',
  'Ready': '就绪',
  'Reconnect': '重新连接',
  'Refreshing...': '正在刷新...',
  'Remove prompt': '移除提示词',
  'Replies': '回复',
  'Reminders': '提醒',
  'Research public posts, draft replies, and keep social workflows reviewable.': '研究公开帖子、起草回复，并让社交流程可审查。',
  'Reset': '重置',
  'Reset-history refs': '重置历史引用',
  'Resources': '资源',
  'Review Worktree Changes': '审查工作树变更',
  'Review Worktree Changes (Open)': '审查工作树变更（已打开）',
  'Scheduled work': '计划任务',
  'Schedule': '计划',
  'Search': '搜索',
  'Search Composio connectors': '搜索 Composio 连接器',
  'Search Composio connectors...': '搜索 Composio 连接器...',
  'Search apps': '搜索应用',
  'Search apps...': '搜索应用...',
  'Search commits...': '搜索提交...',
  'Search communities, inspect posts, and prepare natural replies before posting.': '搜索社区、查看帖子，并在发布前准备自然的回复。',
  'Search options...': '搜索选项...',
  'Search plugins': '搜索插件',
  'Search plugins...': '搜索插件...',
  'Select...': '选择...',
  'Select a branch.': '选择一个分支。',
  'Send feedback': '发送反馈',
  'Share': '分享',
  'Show {sha} files': '显示 {sha} 的文件',
  'Showing {loaded} / {total} connectors': '正在显示 {loaded} / {total} 个连接器',
  'Showing {loaded} connectors': '正在显示 {loaded} 个连接器',
  'Skills directory': '技能目录',
  'Skills & Apps': '技能和应用',
  'Sort Composio connectors': '排序 Composio 连接器',
  'Sort apps': '排序应用',
  'Sort plugins': '排序插件',
  'Starting...': '正在启动...',
  'Status unknown': '状态未知',
  'Target': '目标',
  'This browser blocked sharing the ZIP. Use Download instead.': '此浏览器阻止了 ZIP 分享。请改用下载。',
  'Tools': '工具',
  'Tracked changes must be committed, stashed, or discarded before switching or resetting. Untracked files are allowed unless Git would overwrite them.': '切换或重置前必须提交、暂存或丢弃已跟踪的更改。未跟踪文件可以保留，除非 Git 会覆盖它们。',
  'Try it!': '试试看！',
  'Uncommitted changes': '未提交更改',
  'Unknown': '未知',
  'Use the Composio CLI skill with the {name} connector ({slug}). Start by listing what it can do here, mention the current connection status, and suggest one safe command I can run now.': '使用 Composio CLI 技能处理 {name} 连接器（{slug}）。先列出它在这里能做什么，说明当前连接状态，并建议一个我现在可以安全运行的命令。',
  'Use a thread or project menu to add an automation.': '使用线程或项目菜单添加自动化。',
  'Useful tools': '常用工具',
  'Videos': '视频',
  'Videos, channels, comments': '视频、频道、评论',
  'Weekly': '每周',
  '{count} connected accounts': '已连接 {count} 个账户',
  '{count} resources': '{count} 个资源',
  '{count} tools': '{count} 个工具',
  '{count} triggers': '{count} 个触发器',
  '{name} app {state}': '{name} 应用已{state}',
  '{name} plugin installed': '{name} 插件已安装',
  '{name} plugin uninstalled': '{name} 插件已卸载',
  '{name} plugin {state}': '{name} 插件已{state}',
  'active': '个启用',
  'current': '当前',
  'org {id}': '组织 {id}',
  'paused': '个暂停',
  'remote': '远程',
  'total': '总计',
  'https://api.example.com/v1': 'https://api.example.com/v1',
  'sk-...': 'sk-...',
  'sk-or-v1-... (required for OpenRouter)': 'sk-or-v1-...（OpenRouter 必填）',
}

const LANGUAGE_LABELS: Record<UiLanguage, string> = {
  en: 'English',
  'zh-CN': '简体中文',
}

function readStoredLanguage(): UiLanguage {
  if (typeof window === 'undefined') return 'en'
  const raw = window.localStorage.getItem(UI_LANGUAGE_STORAGE_KEY)?.trim()
  return raw === 'zh-CN' ? 'zh-CN' : 'en'
}

const currentLanguage = ref<UiLanguage>(readStoredLanguage())

function applyDocumentLanguage(language: UiLanguage): void {
  if (typeof document === 'undefined') return
  document.documentElement.lang = language === 'zh-CN' ? 'zh-CN' : 'en'
  document.documentElement.dataset.uiLanguage = language
}

applyDocumentLanguage(currentLanguage.value)

function formatTemplate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => String(params[key] ?? ''))
}

export function setUiLanguage(language: UiLanguage): void {
  currentLanguage.value = language
  applyDocumentLanguage(language)
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(UI_LANGUAGE_STORAGE_KEY, language)
  }
}

export function t(message: string, params?: Record<string, string | number>): string {
  const translated = currentLanguage.value === 'zh-CN' ? (zhCN[message] ?? message) : message
  return formatTemplate(translated, params)
}

export function useUiLanguage() {
  return {
    uiLanguage: currentLanguage,
    uiLanguageOptions: [
      { value: 'en', label: LANGUAGE_LABELS.en },
      { value: 'zh-CN', label: LANGUAGE_LABELS['zh-CN'] },
    ] as Array<{ value: UiLanguage; label: string }>,
    t,
    setUiLanguage,
  }
}
